### ISSUE TITLE
Problem with TIMESTAMP and DATETIME in MySQL

### ISSUE THREAD

**Issue by alessandrolattao** [aws-samples/rds-snapshot-export-to-s3-pipeline#4] opened 2020-07-30 11:21 UTC
Hello, MySQL TIMESTAMPs and DATETIMEs are mapped to parquet TIMESTAMP_MICROS during exportation, as stated here:
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/USER_ExportSnapshot.html#USER_ExportSnapshot.data-types

The problem is that "Currently, Amazon Athena and AWS Glue can handle only millisecond precision for TIMESTAMP values", as stated here: https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Target.S3.html#CHAP_Target.S3.Configuring 

The exportation process seems to miss an option to map those data types to TIMESTAMP_MILLIS during exportation and this cause dates to be completely screwed in Athena.

:cry:

**Comment by michaelmoussa** [comment] 2020-07-31 22:52
Thanks for catching and reporting this, @alessandrolattao! While researching the issue, I found [this thread](https://forums.aws.amazon.com/thread.jspa?messageID=934595) on the Athena discussion forums you might want to read through for additional information. The summary though is that since Athena's query engine is based on Presto, and Presto supports millisecond precision for timestamps, they look don't look correct when you're viewing them in Athena.

The easiest workaround I found for this (assuming your use case allows it) is to convert the timestamps when displaying them.

So, instead of:

```sql
SELECT ts FROM test_db.test_table LIMIT 1;
+52552-05-07 04:06:40.000
```

you could do:

```sql
SELECT from_unixtime(to_unixtime(ts)/1000) AS ts FROM test_db.test_table LIMIT 1
2020-07-31 19:45:22.000
```

I'm going to close this issue since there's not really anything that can be done within the scope of this example implementation to address the root cause; however, I'll raise the issue internally so the service team is aware.

**Closed** 2020-07-31 22:52 UTC
